spring:
  profiles:
    active: test

---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    show_sql: true
    hbm2ddl.auto: create-drop
    cache.use_second_level_cache: true
    cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    cache.use_query_cache: true

  h2:
    console:
      enabled: true
      path: /h2-console

